language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install apgdiff
  - "pip install -e .[tests]"
  - "pip install flake8 psycopg2"
before_script:
  - createdb alps_test -U postgres
  - createdb alembic_test -U postgres
script:
  - alps migration postgresql:///alembic_test "alembic upgrade head"
  - alps migration postgresql:///alembic_test "alembic downgrade 56c02a15aac"
  - alps migration postgresql:///alembic_test "alembic upgrade head"
  - ./check_migration.sh postgresql:///alembic_test diff.sql
  - hooks/pre-commit
  - py.test -vv --duration=20 --database-url='postgresql:///alps_test'
  - py.test -vv --duration=20
